### ISSUE TITLE
Update dependencies to Make Maven compatible

### ISSUE THREAD

**Issue by dukescript** [UltraMixer/FlexBoxFX#3]
The project is using gradle for build, which introduces dependency version numbers that are not resolvable by Maven, e.g.:

    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-collections4</artifactId>
      <version>4.1+</version>
      <scope>compile</scope>
    </dependency>

Version number "4.1+" is problematic. Please change to 4.1 or a range to make usable from Maven projects.

**Comment by tobium** [comment]
no problem. I will change it.

**Comment by dukescript** [comment]
That was quick :-), thanks!
