### ISSUE TITLE
FlexBoxFX can not be found

### ISSUE THREAD

**Issue by TioCoding** [UltraMixer/FlexBoxFX#4]
Hello, in the mvnrepository can not find the FlexBoxFx.

https://mvnrepository.com/search?q=FlexBoxFX

**Comment by bendem** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/onexip/FlexBoxFX/

It's not in central, it's in https://oss.sonatype.org/content/repositories/snapshots (as mentioned in the README).
